name: Generate Stable Database

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Setup
        run: |
          sudo apt-get update
          sudo apt install maven unzip

      - name: Start ClamAV daemon clamd
        uses: toblux/start-clamd-github-action@v0.2.1
        with:
          db_main: true
          db_daily: true
      
      - name: Organize Directories & Static Sources
        run: |
          mkdir -p "${{ github.workspace }}/raw/"
          mkdir -p "${{ github.workspace }}/exclusions/"
          mkdir -p "${{ github.workspace }}/various/"

          cp ${{ github.workspace }}/static/* "${{ github.workspace }}/raw/"
      
      - name: DATABASE PREPARATION - ClamAV
        run: |
          mkdir /tmp/mss
          cd /tmp/mss
          cp /var/lib/clamav/main.c*d .
          cp /var/lib/clamav/daily.c*d .
          sigtool -u main.c*d
          sigtool -u daily.c*d

          mv /tmp/mss/*.fp* "${{ github.workspace }}/exclusions/"
          mv /tmp/mss/*.hsb "${{ github.workspace }}/raw/"
          mv /tmp/mss/*.hdb "${{ github.workspace }}/raw/"
          mv /tmp/mss/*.hdu "${{ github.workspace }}/raw/"
          mv /tmp/mss/*.hsu "${{ github.workspace }}/raw/"

      - name: DATABASE PREPARATION - ThreatView
        run: |
          wget "https://threatview.io/Downloads/MD5-HASH-ALL.txt" -O - | sed 's/MD5 of //' >> "${{ github.workspace }}/various/threatview.md5"
          wget "https://threatview.io/Downloads/SHA-HASH-FEED.txt" -O - >> "${{ github.workspace }}/various/threatview.sha1"

          sort -u -o "${{ github.workspace }}/raw/threatview.md5" "${{ github.workspace }}/various/threatview.md5"
          sort -u -o "${{ github.workspace }}/raw/threatview.sha1" "${{ github.workspace }}/various/threatview.sha1"

      - name: DATABASE PREPARATION - ThreatFox
        run: |
          wget "https://threatfox.abuse.ch/export/csv/sha256/full/" -O "${{ github.workspace }}/various/download_threatfox.zip"
          unzip "${{ github.workspace }}/various/download_threatfox.zip" -d "${{ github.workspace }}/various/"
          tail -n +10 "${{ github.workspace }}/various/full_sha256.csv" | awk '{ print $4 } ' | sed 's/^"//' | sed 's/",$//' > "${{ github.workspace }}/raw/threatfox.sha256"

      - name: DATABASE PREPARATION - MalwareBazaar
        run: |
          wget "https://bazaar.abuse.ch/export/txt/sha256/full/" -O "${{ github.workspace }}/various/download_bazaar.zip"
          unzip "${{ github.workspace }}/various/download_bazaar.zip" -d "${{ github.workspace }}/various/"
          mv "${{ github.workspace }}/various/full_sha256.txt" > "${{ github.workspace }}/raw/malware_bazaar.sha256"

      - name: DATABASE PREPARATION - CyberCure
        run: |
          wget "https://api.cybercure.ai/feed/get_hash?type=csv" -O - | sed 's/,/\n/g' >> "${{ github.workspace }}/various/cybercure.md5"
          sort -u -o "${{ github.workspace }}/raw/cybercure.md5" "${{ github.workspace }}/various/cybercure.md5"

      - name: DATABASE PREPARATION - Stalkerware
        run: |
          wget "https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/refs/heads/master/samples.csv" -O "${{ github.workspace }}/various/stalkerware.csv"
          while IFS=, read -r col1SHA col2Package col3Certificate col4Version col5Name
          do
            if [ -n "$col1SHA" ] && [ -n "$col5Name" ]; then
              echo "$col1SHA:0:$col5Name" >> "${{ github.workspace }}/raw/stalkerware.hsb";
            fi;
          done < "${{ github.workspace }}/various/stalkerware.csv";
          sed -i '1d' "${{ github.workspace }}/raw/stalkerware.hsb";

      - name: GENERATE HYPATIA SIGNATURE DATABASES 
        run: |
          mvn -q -B --no-transfer-progress clean compile exec:java -Dexec.mainClass="org.maintainteam.hypatiadatabases.App" -Dexec.args="${{ github.workspace }}/raw/" > "${{ github.workspace }}/various/generation_report.txt"
          cat "${{ github.workspace }}/various/generation_report.txt"
          echo "<pre>" >> "${{ github.workspace }}/various/generation_report.html"
          cat "${{ github.workspace }}/various/generation_report.txt" >> "${{ github.workspace }}/various/generation_report.html"
          echo "</pre>" >> "${{ github.workspace }}/various/generation_report.html"
          
      - name: Debug Info
        run: |
          ls -hla "${{ github.workspace }}/various/"
          ls -hla "${{ github.workspace }}/raw/"
          ls -hla "${{ github.workspace }}/exclusions/"
          tree -a "${{ github.workspace }}"

      - name: Select files to use
        run: |
          mkdir -p "${{ github.workspace }}/deploy"
          cp "${{ github.workspace }}/raw/hypatia-domains-bloom.bin" "${{ github.workspace }}/deploy"
          cp "${{ github.workspace }}/raw/hypatia-md5-bloom.bin" "${{ github.workspace }}/deploy"
          cp "${{ github.workspace }}/raw/hypatia-sha1-bloom.bin" "${{ github.workspace }}/deploy"
          cp "${{ github.workspace }}/raw/hypatia-sha256-bloom.bin" "${{ github.workspace }}/deploy"
          cp "${{ github.workspace }}/various/generation_report.html" "${{ github.workspace }}/deploy"

          date > "${{ github.workspace }}/deploy/generation_time.html"
      
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ github.workspace }}/deploy"
          force_orphan: true
  

  sign:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: generate

    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages  

      - name: Import GPG Key
        run: |
          mkdir -p "/tmp/sign"
          cd "/tmp/sign"
          echo "Created a test gpg key for testing-only. If you find any problem, please report !"
          
          # REVIEW: POSSIBLE SECURITY PROBLEM ????
          echo "${{ secrets.TEST_GPG_SECRET_BASE64 }}" | base64 -d > "/tmp/sign/private.key"
          gpg --batch --import "/tmp/sign/private.key"
          rm "/tmp/sign/private.key"

      - name: Generate Public Key & Signed Files
        run: | 
          gpg --batch --export -a --armor "${{ secrets.TEST_GPG_ID }}" > "${{ github.workspace }}/gpg.key"

          gpg --batch --dry-run -v --import gpg.key 2>"${{ github.workspace }}/file.txt"
          cat "${{ github.workspace }}/file.txt" | grep -o '/[^ ]*' | cut -c2- > "${{ github.workspace }}/sign_key.txt"
          rm "${{ github.workspace }}/file.txt"
          # EXPORTS DATABASE SIGNING KEY: C335CDA7A1C0F66B
          
          # REVIEW: POSSIBLE SECURITY PROBLEM ????
          echo "${{ secrets.TEST_GPG_PASS }}" | gpg --pinentry-mode=loopback --batch -u "${{ secrets.TEST_GPG_ID }}" --passphrase-fd 0 --output "${{ github.workspace }}/hypatia-sha1-bloom.bin.sig" --detach-sig "${{ github.workspace }}/hypatia-sha1-bloom.bin"
          echo "${{ secrets.TEST_GPG_PASS }}" | gpg --pinentry-mode=loopback --batch -u "${{ secrets.TEST_GPG_ID }}" --passphrase-fd 0 --output "${{ github.workspace }}/hypatia-sha256-bloom.bin.sig" --detach-sig "${{ github.workspace }}/hypatia-sha256-bloom.bin"
          echo "${{ secrets.TEST_GPG_PASS }}" | gpg --pinentry-mode=loopback --batch -u "${{ secrets.TEST_GPG_ID }}" --passphrase-fd 0 --output "${{ github.workspace }}/hypatia-md5-bloom.bin.sig" --detach-sig "${{ github.workspace }}/hypatia-md5-bloom.bin"
          echo "${{ secrets.TEST_GPG_PASS }}" | gpg --pinentry-mode=loopback --batch -u "${{ secrets.TEST_GPG_ID }}" --passphrase-fd 0 --output "${{ github.workspace }}/hypatia-domains-bloom.bin.sig" --detach-sig "${{ github.workspace }}/hypatia-domains-bloom.bin"

      - name: Create index.html   
        run: |
          cd "${{ github.workspace }}"
          find . -type d -print -exec sh -c 'tree "$0" \
            -H "." \
            -L 1 \
            --noreport \
            --houtro "" \
            --dirsfirst \
            --charset utf-8 \
            -I "index.html" \
            -T "Files" \
            --ignore-case \
            --timefmt "%d-%b-%Y %H:%M" \
            -s \
            -D \
            -o "$0/index.html"' {} \; 
          
          echo "<br><hr>Signing Key: " >> index.html
          cat "${{ github.workspace }}/sign_key.txt" >> index.html
          echo "<br>Current Databases & Index generated with <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">CI</a>" >> index.html
          echo "<hr><br>" >> index.html
          cat "${{ github.workspace }}/generation_report.html" >> "${{ github.workspace }}/index.html"
       
      - name: Deploy to Github pages (with signatures and index)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ github.workspace }}"
          force_orphan: false



