name: signtest

on:
  workflow_dispatch:

jobs:
  
  sign:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages  

      - name: WIP Sign
        run: |
          export GPG_TTY=$(tty)  # https://stackoverflow.com/questions/72445825/gpg-error-inappropriate-ioctl-for-device
          
          mkdir -p "/tmp/sign"
          cd "/tmp/sign"
          echo "Created a test gpg key for testing-only. If you find any problem, please report !"
          # C335CDA7A1C0F66B
          echo "${{ secrets.TEST_GPG_SECRET_BASE64 }}" | base64 -d > "/tmp/sign/private.key"
          # FIXME: IS IT SAFE ????
          gpg --batch --import "/tmp/sign/private.key"
          rm "/tmp/sign/private.key"

          cd "${{ github.workspace }}"
          gpg --batch --export -a --armor "${{ secrets.TEST_GPG_ID }}" > "${{ github.workspace }}/gpg.key"
          
          # FIXME: IS THESE SAFE ???
          echo "${{ secrets.TEST_GPG_PASS }}" | gpg --batch -u "${{ secrets.TEST_GPG_ID }}" --passphrase-fd 0 --output hypatia-sha1-bloom.bin.sig --detach-sig hypatia-sha1-bloom.bin
          echo "${{ secrets.TEST_GPG_PASS }}" | gpg --batch -u "${{ secrets.TEST_GPG_ID }}" --passphrase-fd 0 --output hypatia-sha256-bloom.bin.sig --detach-sig hypatia-sha256-bloom.bin
          echo "${{ secrets.TEST_GPG_PASS }}" | gpg --batch -u "${{ secrets.TEST_GPG_ID }}" --passphrase-fd 0 --output hypatia-md5-bloom.bin.sig --detach-sig hypatia-md5-bloom.bin
          echo "${{ secrets.TEST_GPG_PASS }}" | gpg --batch -u "${{ secrets.TEST_GPG_ID }}" --passphrase-fd 0 --output hypatia-domains-bloom.bin.sig --detach-sig hypatia-domains-bloom.bin

      - name: Create index.html   
        run: |
          cd "${{ github.workspace }}"
          find . -type d -print -exec sh -c 'tree "$0" \
            -H "." \
            -L 1 \
            --noreport \
            --houtro "" \
            --dirsfirst \
            --charset utf-8 \
            -I "index.html" \
            -T "Files" \
            --ignore-case \
            --timefmt "%d-%b-%Y %H:%M" \
            -s \
            -D \
            -o "$0/index.html"' {} \; 
          
          echo "<br><hr><br>" >> index.html
          cat "${{ github.workspace }}/generation_report.html" >> "${{ github.workspace }}/index.html"
       
      - name: Deploy to Github pages (with signatures and index)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ github.workspace }}"
          force_orphan: false





