name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ClamAV daemon clamd
        uses: toblux/start-clamd-github-action@v0.2.1
        with:
          db_main: true
          db_daily: true
      
      - name: Tests
        run: |
          mkdir -p "${{ github.workspace }}/output"
          origDir="${{ github.workspace }}/output"

          ls -hla /var/lib/clamav

          sudo apt install

          mkdir /tmp/mss
          cd /tmp/mss
          cp /var/lib/clamav/main.c*d .
          cp /var/lib/clamav/daily.c*d .
          sigtool -u main.c*d
          sigtool -u daily.c*d

          mv /tmp/mss/*.fp* "$origDir/exclusions/"
          mv /tmp/mss/*.hsb "$origDir/raw/"
          mv /tmp/mss/*.hdb "$origDir/raw/"
          mv /tmp/mss/*.hdu "$origDir/raw/"
          mv /tmp/mss/*.hsu "$origDir/raw/"



