name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maven Setup
        run: |
          sudo apt-get update
          sudo apt install maven

      - name: Start ClamAV daemon clamd
        uses: toblux/start-clamd-github-action@v0.2.1
        with:
          db_main: true
          db_daily: true
      
      - name: DATABASE PREPARATION - ClamAV
        run: |
          mkdir -p "${{ github.workspace }}/raw/"
          mkdir -p "${{ github.workspace }}/exclusions/"

          mkdir /tmp/mss
          cd /tmp/mss
          cp /var/lib/clamav/main.c*d .
          cp /var/lib/clamav/daily.c*d .
          sigtool -u main.c*d
          sigtool -u daily.c*d

          mv /tmp/mss/*.fp* "${{ github.workspace }}/exclusions/"
          mv /tmp/mss/*.hsb "${{ github.workspace }}/raw/"
          mv /tmp/mss/*.hdb "${{ github.workspace }}/raw/"
          mv /tmp/mss/*.hdu "${{ github.workspace }}/raw/"
          mv /tmp/mss/*.hsu "${{ github.workspace }}/raw/"

      - name: DATABASE PREPARATION - ThreatView
        run: |
          wget "https://threatview.io/Downloads/MD5-HASH-ALL.txt" -O - | sed 's/MD5 of //' >> "${{ github.workspace }}/raw/threatview.md5"
          wget "https://threatview.io/Downloads/SHA-HASH-FEED.txt" -O - >> "${{ github.workspace }}/raw/threatview.sha1"

          sort -u -o "${{ github.workspace }}/raw/threatview.md5" "${{ github.workspace }}/raw/threatview.md5"
          sort -u -o "${{ github.workspace }}/raw/threatview.sha1" "${{ github.workspace }}/raw/threatview.sha1"

      - name: DATABASE PREPARATION - ThreatFox
        run: |
          sudo apt install unzip
      
          wget "https://threatfox.abuse.ch/export/csv/sha256/full/" -O "${{ github.workspace }}/raw/download.zip"
          unzip "${{ github.workspace }}/raw/download.zip" -d "${{ github.workspace }}/raw/"
          tail -n +10 "${{ github.workspace }}/raw/full_sha256.csv" | awk '{ print $4 } ' | sed 's/^"//' | sed 's/",$//' > "${{ github.workspace }}/raw/threatfox.sha256"

      - name: GENERATE HYPATIA SIGNATURE DATABASES 
        run: |
          mvn clean compile exec:java -Dexec.mainClass="org.maintainteam.hypatiadatabases.App" -Dexec.args="${{ github.workspace }}/raw/"
          ls -hla "${{ github.workspace }}/raw/"
          ls -hla "${{ github.workspace }}/exclusions/"

      - name: Select files to use
        run: |
          mkdir -p "${{ github.workspace }}/deploy"
          cp "${{ github.workspace }}/raw/hypatia-domains-bloom.bin" "${{ github.workspace }}/deploy"
          cp "${{ github.workspace }}/raw/hypatia-md5-bloom.bin" "${{ github.workspace }}/deploy"
          cp "${{ github.workspace }}/raw/hypatia-sha1-bloom.bin" "${{ github.workspace }}/deploy"
          cp "${{ github.workspace }}/raw/hypatia-sha256-bloom.bin" "${{ github.workspace }}/deploy"
          
          cd "${{ github.workspace }}/deploy"
          find . -type d -print -exec sh -c 'tree "$0" \
            -H "." \
            -L 1 \
            --noreport \
            --houtro "" \
            --dirsfirst \
            --charset utf-8 \
            -I "index.html" \
            -T "Custom Title" \
            --ignore-case \
            --timefmt "%d-%b-%Y %H:%M" \
            -s \
            -D \
            -o "$0/index.html"' {} \; 
      
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ github.workspace }}/deploy"
          force_orphan: true
      






