name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maven Setup
        run: |
          sudo apt-get update
          sudo apt install maven

      - name: Start ClamAV daemon clamd
        uses: toblux/start-clamd-github-action@v0.2.1
        with:
          db_main: true
          db_daily: true
      
      - name: Generate Clamav
        run: |
          mkdir -p "${{ github.workspace }}/raw/"
          mkdir -p "${{ github.workspace }}/exclusions/"

          mkdir /tmp/mss
          cd /tmp/mss
          cp /var/lib/clamav/main.c*d .
          cp /var/lib/clamav/daily.c*d .
          sigtool -u main.c*d
          sigtool -u daily.c*d

          mv /tmp/mss/*.fp* "${{ github.workspace }}/exclusions/"
          mv /tmp/mss/*.hsb "${{ github.workspace }}/raw/"
          mv /tmp/mss/*.hdb "${{ github.workspace }}/raw/"
          mv /tmp/mss/*.hdu "${{ github.workspace }}/raw/"
          mv /tmp/mss/*.hsu "${{ github.workspace }}/raw/"

      - name: Maven Run
        run: |
          mvn clean compile exec:java -Dexec.mainClass="org.maintainteam.hypatiadatabases.App" -Dexec.args="${{ github.workspace }}/raw/"    
          ls -lha
          ls -lha raw
          ls -lha exclusions 




