name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install clamav
          sudo freshclam

          
