name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  BASE: "${{ github.workspace }}/src/main/java/org/maintainteam/hypatiadatabases"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maven Setup
        run: |
          sudo apt-get update
          sudo apt install maven

      - name: Start ClamAV daemon clamd
        uses: toblux/start-clamd-github-action@v0.2.1
        with:
          db_main: true
          db_daily: true
      
      - name: Generate Clamav
        run: |
          mkdir -p "${{ github.workspace }}/output"
          origDir="${{ github.workspace }}/output"
          mkdir -p "$origDir/exclusions/"
          mkdir -p "$origDir/raw/"

          ls -hla /var/lib/clamav

          mkdir /tmp/mss
          cd /tmp/mss
          cp /var/lib/clamav/main.c*d .
          cp /var/lib/clamav/daily.c*d .
          sigtool -u main.c*d
          sigtool -u daily.c*d

          mv /tmp/mss/*.fp* "$origDir/exclusions/"
          mv /tmp/mss/*.hsb "$origDir/raw/"
          mv /tmp/mss/*.hdb "$origDir/raw/"
          mv /tmp/mss/*.hdu "$origDir/raw/"
          mv /tmp/mss/*.hsu "$origDir/raw/"

      - name: Maven Run
        run: |
          mvn clean compile exec:java -Dexec.mainClass="org.maintainteam.hypatiadatabases.App" -Dexec.args="$origDir/raw/"



