name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ClamAV
        run: |
          apt-get update
          apt-get install clamav-daemon
          systemctl stop clamav-freshclam
          systemctl status clamav-freshclam
          freshclam -F
          ls -la /var/lib/clamav

